// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9aGxP_7Lg_HeTzHGb_8B8_C_kvMLJ3-A',
    appId: '1:226412116522:web:924554e7c0f22575f26153',
    messagingSenderId: '226412116522',
    projectId: 'bekhar-85a2b',
    authDomain: 'bekhar-85a2b.firebaseapp.com',
    storageBucket: 'bekhar-85a2b.appspot.com',
    measurementId: 'G-EGKGRVVSKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR66h8oGH35ihtcPC1rEAgPuvcdq2cH90',
    appId: '1:226412116522:android:901df21235fc8e2af26153',
    messagingSenderId: '226412116522',
    projectId: 'bekhar-85a2b',
    storageBucket: 'bekhar-85a2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBELqyDphMcuqE53odnkn4WVN0kEOVYjKE',
    appId: '1:226412116522:ios:3b02c5012d2d0edbf26153',
    messagingSenderId: '226412116522',
    projectId: 'bekhar-85a2b',
    storageBucket: 'bekhar-85a2b.appspot.com',
    androidClientId: '226412116522-7nkklu6f7a1cc04m0ueh9phfl9f41mqc.apps.googleusercontent.com',
    iosClientId: '226412116522-vds7sbnq6lptr843q1bg71cr5a9523bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bekhar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBELqyDphMcuqE53odnkn4WVN0kEOVYjKE',
    appId: '1:226412116522:ios:3b02c5012d2d0edbf26153',
    messagingSenderId: '226412116522',
    projectId: 'bekhar-85a2b',
    storageBucket: 'bekhar-85a2b.appspot.com',
    androidClientId: '226412116522-7nkklu6f7a1cc04m0ueh9phfl9f41mqc.apps.googleusercontent.com',
    iosClientId: '226412116522-vds7sbnq6lptr843q1bg71cr5a9523bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bekhar',
  );
}
